version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - mkdir -p ./gen/go
      - protoc --proto_path=./proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative ./proto/sso/sso.proto

  clean:
    desc: "Clean generated files"
    cmds:
      - rm -rf ./gen/go